#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec jekyll serve --detach
sleep 3
bundle exec rake -t -v
bundle exec htmlproofer --empty-alt-ignore ./_site
pkill -f jekyll
